export const ADD_USERS = 'ADD_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILED = 'USERS_FAILED';

export const ADD_USER_DETAILS = 'ADD_USER_DETAILS';
export const USER_DETAILS_LOADING = 'USER_DETAILS_LOADING';